services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cakeshop
    volumes:
      - C:\Gehan\Personal\docker\postgres_data:/var/lib/postgresql/data
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cakeshop
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - C:\Gehan\Personal\docker\mysql_data:/var/lib/mysql
    restart: always